### ISSUE TITLE
Need some guide on using this.

### ISSUE THREAD

**Issue by miroccur** [tihmstar/noncestatistics#5]
Hi developers! I'm trying using this tool to collect statistics of my iPhone 7, when I plug my iPhone 7 in and run ./noncestatistics , it simply said 'ERROR: Unable to discover device model'.

So here's my question: Does this tool require a jailbreak or it doesn't support iPhone 7? Or I should manually boot my iPhone 7 into recovery mode but not let this tool MAKE my iPhone 7 get into that mode?

Thanks

**Comment by RaisinGod** [comment]
Do ./noncestatistics -h

Read the help and manually specify your device and stuff.

**Comment by miroccur** [comment]
@RaisinGod Still having problem, I input ECID, but it can never detect device model.

**Comment by miroccur** [comment]
Even I am in recovery mode, this won't work

**Comment by gugucarv** [comment]
me too

i let noncestatistics working a lot and got 2281 apnonces. no one is equal. Each 2281 is a unique nonce. this way i will not be able to downgrade. what should i do?

**Comment by tihmstar** [comment]
This might actually be a bug in noncestatistics or an outdated version of libirecovery the current build is linked against. I remember having similar issues.

**Comment by miroccur** [comment]
thanks @tihmstar . It's my fault I didn't mention I found noncestatistics from api.tihmstar.net works. I think you can close this issue now.

**Comment by miroccur** [comment]
Thanks @tihmstar , but it's my fault I found noncestatistics from api.tihmstar.net works later. Maybe you can close this issue now. (anyway I do not know the reason causing it do/do not work, you may still need a little bit research)
